FM-149 | Backend request to reset password
Findock/findme-mobile-app pull request #51
Opened 2022-03-30 19:29 UTC by heavycavalry

2022-03-30 21:03 UTC, marcelinax requested changes

2022-03-30 21:03 UTC, marcelinax commented on screens/ForgotPassword.screen.jsx
> +    try {
moga Ci lecieć takie błedy jak u góry wysłałam i wtedy walidacja którą zrobiła jest okey, ma sie wyświetlać taki error, ale jeżeli użytkownik podał prawidłowy mail ale nie istnieje on  w bazie find me to leci taki error "User with this email does not exist" wiec tutaj musisz obsłużyć innego errora

2022-03-31 01:10 UTC, heavycavalry commented
[image: image.png]

czw., 31 mar 2022 o 01:45 sonarcloud[bot] ***@***.***>
napisał(a):

> Kudos, SonarCloud Quality Gate passed!    [image: Quality Gate passed]
> <https://sonarcloud.io/dashboard?id=Findock_findme-mobile-app&pullRequest=51>
>
> [image: Bug]
> <https://sonarcloud.io/project/issues?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=BUG> [image:
> A]
> <https://sonarcloud.io/project/issues?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=BUG> 0
> Bugs
> <https://sonarcloud.io/project/issues?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=BUG>
> [image: Vulnerability]
> <https://sonarcloud.io/project/issues?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=VULNERABILITY> [image:
> A]
> <https://sonarcloud.io/project/issues?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=VULNERABILITY> 0
> Vulnerabilities
> <https://sonarcloud.io/project/issues?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=VULNERABILITY>
> [image: Security Hotspot]
> <https://sonarcloud.io/project/security_hotspots?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=SECURITY_HOTSPOT> [image:
> A]
> <https://sonarcloud.io/project/security_hotspots?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=SECURITY_HOTSPOT> 0
> Security Hotspots
> <https://sonarcloud.io/project/security_hotspots?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=SECURITY_HOTSPOT>
> [image: Code Smell]
> <https://sonarcloud.io/project/issues?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=CODE_SMELL> [image:
> A]
> <https://sonarcloud.io/project/issues?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=CODE_SMELL> 0
> Code Smells
> <https://sonarcloud.io/project/issues?id=Findock_findme-mobile-app&pullRequest=51&resolved=false&types=CODE_SMELL>
>
> [image: No Coverage information]
> <https://sonarcloud.io/component_measures?id=Findock_findme-mobile-app&pullRequest=51>
> No Coverage information
> [image: 0.0%]
> <https://sonarcloud.io/component_measures?id=Findock_findme-mobile-app&pullRequest=51&metric=new_duplicated_lines_density&view=list> 0.0%
> Duplication
> <https://sonarcloud.io/component_measures?id=Findock_findme-mobile-app&pullRequest=51&metric=new_duplicated_lines_density&view=list>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Findock/findme-mobile-app/pull/51#issuecomment-1083787562>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALICZ7SPMV7HRWPHCOVZAC3VCTRSLANCNFSM5SC6IEPA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-31 16:22 UTC, marcelinax requested changes

2022-03-31 16:22 UTC, marcelinax commented on screens/ForgotPassword.screen.jsx
>    const onSubmit = async () => {
error modal ma się pokazywać tylko wtedy jeżeli leci błąd inny niż 400 lub 404

2022-03-31 16:22 UTC, marcelinax commented on screens/ForgotPassword.screen.jsx
>    const onSubmit = async () => {
musisz to wyłapać w checEmailValidation i tam wsadzić w else setShowErrorModal na true i wywalić go z catcha

2022-03-31 16:22 UTC, marcelinax commented on screens/ForgotPassword.screen.jsx
>    const onSubmit = async () => {
http://localhost:3005/api/#/auth/FindMeAuthController_sendPasswordResetLinkEmail na dole masz sprawdzanie jakie odpowiedzi lecą na request

2022-03-31 21:40 UTC, marcelinax requested changes

2022-04-01 10:34 UTC, heavycavalry commented on screens/ForgotPassword.screen.jsx
> +    } else { setShowErrorModal(true); }
ustawilam sobie eslint pod save ale cos rzeczywiscie nie idzie, teraz pracuje w webstormie i troche mi sie pozmienialo. Ogarne

2022-04-01 16:27 UTC, marcelinax approved these changes

2022-04-01 16:27 UTC, merged