FM-177 | Backend request to change password
Findock/findme-mobile-app pull request #53
Opened 2022-04-01 21:37 UTC by heavycavalry

2022-04-01 22:07 UTC, marcelinax requested changes

2022-04-01 22:07 UTC, marcelinax commented on screens/ChangePassword.screen.jsx
> +    if (dataForm.newPassword !== confirmNewPassword) {
1. Input stare hasło wywala walidacje że hasło jest za krótkie, jedyne co ma robić to walidować po tym, że jest niezgodne z obecnym hasłem
2.  dałam dwa różne nowe hasła i przeszedł request => to czy nowe hasła się różnia trzeba walidować w onSubmit przed try. Wsadzić to w if else 
3. Errory powinny czyścić sie w try na końcu czyli po setPasswordChangeSuccessModalVisible(true)

2022-04-01 22:53 UTC, heavycavalry commented on screens/ChangePassword.screen.jsx
> +              imagePath={images.CHANGE_PASSWORD()}
zrobione, na 50 bo udalo mi sie sprawdzic na androidzie i na ios i u mnie to spoko wyglada

2022-04-02 09:32 UTC, marcelinax approved these changes
GJ 🧨

2022-04-02 09:32 UTC, merged