FM-189 | Create your announcements screen
Findock/findme-mobile-app pull request #65
Opened 2022-04-22 21:06 UTC by heavycavalry

2022-04-23 10:55 UTC, marcelinax requested changes

2022-04-23 10:55 UTC, marcelinax commented on screens/YourAnnouncements.screen.jsx
> +          contentContainerStyle={styles.container}
dodaj tutaj jeeszcze:
1. srollEnabled
2.  Spróbuj obsłużyć coś takiego, ze jak Ci się ładują nowe elementy na liście to żeby pokazywał się spinner

2022-04-23 10:55 UTC, marcelinax commented on screens/YourAnnouncements.screen.jsx
> +      {isLoading && <FSpinner style={{ paddingTop: sizes.PADDING_30 }} />}
ten padding jest tutaj zbędny

2022-04-23 10:55 UTC, marcelinax commented on screens/YourAnnouncements.screen.jsx
> +export const YourAnnouncementsScreen = () => {
Ogólnie wygląda okey, więc te listy zamiast za kazdym razem robić wszystko tak samo, to wywal te listy jako jeden komponent np AnnouncementList i daj mu takie propsy żeby z łatwością można było rozróznic co kiedy ma sie dziać czyli np props isMe jako bool. I teraz jeżeli jest na true to robisz takiego fetcha jak jest a jak nie to mu zmieniasz na pobieranie ogłoszeń innego użytkownika. Tak samo bedzie sie wyświetlał komunika jeżeli nie ma żadnych innych ogłoszeń.


Pasowałony też dac jakiś tytuł w headerze w nawigacji na jakiej liście jesteś czyli np jeżeli nie na swojej to Ogłoszenia użytwkonika Dupa a jak na moim to np Moje ogłoszenia. Na  razie sprawdź jak to wygląda a póxbniej podeślij i zobaczymy czy jest sens tak robić. Jak nie to trzeba bedzie to dac jako sticky headeing w flat liscie :D

2022-04-23 10:55 UTC, marcelinax commented on screens/YourAnnouncements.screen.jsx
> +export const YourAnnouncementsScreen = () => {
Bo tam jest już przycisk powrót wiec to może mega słabo wyglądać wiec od razu na Twoim miejscu bym zrobiła to sticky header w liście. Wzoruj się na FmultiSelectOptions, tam jest sticky inpput

2022-04-23 10:55 UTC, marcelinax commented on components/Scoped/Announcement/FAnnouncementCard.jsx
> +              containerStyle={{ width: '90%' }}
słabo to działa na mniejsze urządzenia, potrzebujesz to jakoś inaczej uzależnic, nie od width.  Zamiast tego spróbuj poszukać przyczyny dlaczego samo nie umie zobaczyc że powinno sie przyciać
![image](https://user-images.githubusercontent.com/61546640/164891578-473771d7-f608-4394-aa64-0392363f3ae8.png)
Musisz bardziej zwracać uwage na RWD :D

2022-04-25 12:52 UTC, heavycavalry commented on components/Composition/FHeadingWithIcon.jsx
> +  icon,
done xD

2022-05-10 20:29 UTC, merged